// rp2a03_core\src\apu_frame_counter.rs
// Adapted from TetaNES: https://github.com/lukexor/tetanes/blob/main/tetanes-core/src/apu/frame_counter.rs
//
// APU Frame Counter implementation (NTSC only).
//
// See: <https://www.nesdev.org/wiki/APU_Frame_Counter>

/// The type of frame event generated by the frame counter.
#[derive(Debug, Copy, Clone, PartialEq, Eq)]
pub enum FrameType {
    None,
    Quarter,
    Half,
}

/// APU Frame Counter generates low-frequency clocks for APU channel units.
///
/// See: <https://www.nesdev.org/wiki/APU_Frame_Counter>
#[derive(Debug, Clone)]
pub struct FrameCounter {
    step_cycles: [u32; 6],
    step: usize,
    mode: u8,
    write_buffer: Option<u8>,
    write_delay: u8,
    block_counter: u8,
    cycle: u32,
    inhibit_irq: bool,
    irq_pending: bool,
}

impl FrameCounter {
    // NTSC cycle counts for 4-step and 5-step modes
    const STEP4_CYCLES: [u32; 6] = [7457, 14913, 22371, 29828, 29829, 29830];
    const STEP5_CYCLES: [u32; 6] = [7457, 14913, 22371, 29829, 37281, 37282];

    const FRAME_TYPE: [FrameType; 6] = [
        FrameType::Quarter,
        FrameType::Half,
        FrameType::Quarter,
        FrameType::None,
        FrameType::Half,
        FrameType::None,
    ];

    pub fn new() -> Self {
        Self {
            step_cycles: Self::STEP4_CYCLES,
            step: 0,
            mode: 0,
            write_buffer: None,
            write_delay: 0,
            block_counter: 0,
            cycle: 0,
            inhibit_irq: false,
            irq_pending: false,
        }
    }

    /// Returns whether an IRQ is pending.
    #[inline]
    pub fn irq_pending(&self) -> bool {
        self.irq_pending
    }

    /// Acknowledges (clears) a pending IRQ.
    #[inline]
    pub fn acknowledge_irq(&mut self) {
        self.irq_pending = false;
    }

    fn step_cycles_for_mode(mode: u8) -> [u32; 6] {
        if mode == 0 {
            Self::STEP4_CYCLES
        } else {
            Self::STEP5_CYCLES
        }
    }

    /// On write to $4017
    pub fn write(&mut self, val: u8, cycle: u32) {
        self.write_buffer = Some(val);
        // Writes occurring on odd clocks are delayed
        self.write_delay = if cycle & 0x01 == 0x01 { 4 } else { 3 };
        self.inhibit_irq = val & 0x40 == 0x40; // D6
        if self.inhibit_irq {
            self.irq_pending = false;
        }
    }

    /// Returns true if the frame counter needs to be clocked this cycle.
    #[inline]
    pub fn should_clock(&self, cycles: u32) -> bool {
        self.block_counter > 0
            || self.write_buffer.is_some()
            || (self.cycle + cycles) >= (self.step_cycles[self.step] - 1)
    }

    // mode 0: 4-step  effective rate (approx)
    // ---------------------------------------
    // - - - f f f      60 Hz
    // - l - - l -     120 Hz
    // e e e - e -     240 Hz
    //
    // mode 1: 5-step  effective rate (approx)
    // ---------------------------------------
    // - - - - - -     (interrupt flag never set)
    // - l - - l -     96 Hz
    // e e e - e -     192 Hz
    pub fn clock_with(&mut self, cycles: u32, mut on_clock: impl FnMut(FrameType)) -> u32 {
        let mut cycles_ran = 0;
        let step_cycles = self.step_cycles[self.step];

        if self.cycle + cycles >= step_cycles {
            if !self.inhibit_irq && self.mode == 0 && self.step >= 3 {
                self.irq_pending = true;
            }

            let ty = Self::FRAME_TYPE[self.step];
            if ty != FrameType::None && self.block_counter == 0 {
                on_clock(ty);
                // Do not allow writes to $4017 to clock for the next cycle
                // (odd + following even cycle)
                self.block_counter = 2;
            }

            if step_cycles >= self.cycle {
                cycles_ran = step_cycles - self.cycle;
            }

            self.step += 1;
            if self.step == 6 {
                self.step = 0;
                self.cycle = 0;
            } else {
                self.cycle += cycles_ran;
            }
        } else {
            cycles_ran = cycles;
            self.cycle += cycles_ran;
        }

        if let Some(val) = self.write_buffer {
            self.write_delay -= 1;
            if self.write_delay == 0 {
                self.mode = if val & 0x80 == 0x80 { 1 } else { 0 };
                self.step_cycles = Self::step_cycles_for_mode(self.mode);
                self.step = 0;
                self.cycle = 0;
                self.write_buffer = None;
                if self.mode == 1 && self.block_counter == 0 {
                    // Writing to $4017 with bit 7 set will immediately
                    // generate a quarter/half frame
                    on_clock(FrameType::Half);
                    self.block_counter = 2;
                }
            }
        }

        if self.block_counter > 0 {
            self.block_counter -= 1;
        }

        cycles_ran
    }

    /// Reset all state.
    pub fn reset(&mut self) {
        self.step_cycles = Self::STEP4_CYCLES;
        self.step = 0;
        self.mode = 0;
        self.write_buffer = None;
        self.write_delay = 0;
        self.block_counter = 0;
        self.cycle = 0;
        self.inhibit_irq = false;
        self.irq_pending = false;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_frame_counter_defaults() {
        let fc = FrameCounter::new();
        assert!(!fc.irq_pending());
        assert_eq!(fc.mode, 0);
        assert_eq!(fc.step, 0);
        assert_eq!(fc.cycle, 0);
    }

    #[test]
    fn write_sets_irq_inhibit() {
        let mut fc = FrameCounter::new();
        fc.write(0x40, 0); // D6 = inhibit IRQ
        assert!(fc.inhibit_irq);
    }

    #[test]
    fn write_with_mode_1_triggers_immediate_half_frame() {
        let mut fc = FrameCounter::new();
        fc.write(0x80, 0); // D7 = mode 1

        let mut frame_type_received = FrameType::None;
        // Clock enough times for the write delay to expire
        for _ in 0..4 {
            fc.clock_with(1, |ft| {
                frame_type_received = ft;
            });
        }
        assert_eq!(frame_type_received, FrameType::Half);
    }

    #[test]
    fn quarter_frame_fires_at_correct_cycle() {
        let mut fc = FrameCounter::new();
        let mut received = Vec::new();

        // Clock up to just past the first step boundary (7457 cycles)
        let mut total = 0;
        while total <= 7457 {
            fc.clock_with(1, |ft| {
                received.push(ft);
            });
            total += 1;
        }

        assert!(received.contains(&FrameType::Quarter));
    }

    #[test]
    fn mode_0_generates_irq() {
        let mut fc = FrameCounter::new();
        // Don't inhibit IRQ
        assert!(!fc.inhibit_irq);

        // Clock through all steps of mode 0 until step >= 3
        let mut total = 0u32;
        while total < 30000 {
            fc.clock_with(1, |_| {});
            total += 1;
        }

        assert!(fc.irq_pending());
    }

    #[test]
    fn inhibit_irq_prevents_irq() {
        let mut fc = FrameCounter::new();
        fc.write(0x40, 0); // inhibit IRQ

        // Process write delay
        for _ in 0..4 {
            fc.clock_with(1, |_| {});
        }

        // Clock through entire mode 0 sequence
        let mut total = 0u32;
        while total < 30000 {
            fc.clock_with(1, |_| {});
            total += 1;
        }

        assert!(!fc.irq_pending());
    }

    #[test]
    fn reset_clears_state() {
        let mut fc = FrameCounter::new();
        fc.write(0xC0, 0);
        fc.reset();
        assert_eq!(fc.mode, 0);
        assert!(!fc.irq_pending());
        assert!(!fc.inhibit_irq);
    }
}
