[package]
name = "rp2a03_niceplug"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
rp2a03_core = { workspace = true }
rp2a03_common = { workspace = true }
nice-plug = { workspace = true }
nice-plug-egui = { workspace = true }
egui = { workspace = true }
parking_lot = { workspace = true }
egui_extras = { workspace = true }
image = { workspace = true }