[package]
name = "rp2a03_niceplug"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
rp2a03_core = { path = "../rp2a03_core" }
rp2a03_common = { path = "../rp2a03_common" }
nice-plug = { git = "https://codeberg.org/RustAudio/nice-plug.git" }
nice-plug-egui = { git = "https://codeberg.org/RustAudio/nice-plug.git" }
egui = "0.35.0"
parking_lot = "0.12"